# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deep-genomics',
                'doc_host': 'https://azaidi06.github.io',
                'git_url': 'https://github.com/azaidi06/deep-genomics',
                'lib_path': 'deep_genomics'},
  'syms': {'deep_genomics.core': {'deep_genomics.core.foo': ('core.html#foo', 'deep_genomics/core.py')}}}
